version: 2.1
references:
  yarn_key: &yarn_key v1-dependencies-{{ checksum "yarn.lock" }}

  save_yarn_cache: &save_yarn_cache
    save_cache:
      key: *yarn_key
      paths:
        - node_modules

  restore_yarn_cache: &restore_yarn_cache
    restore_cache:
      key: *yarn_key

jobs:
  build:
    docker:
      - image: circleci/node:12.22.7
    steps:
      - checkout
      - *restore_yarn_cache
      - run: yarn install
      - *save_yarn_cache
      - run: yarn test
      - store_artifacts:
          path: dist
          destination: dist

  publish:
    docker:
      - image: circleci/node:12.22.7
    steps:
      - checkout
      - *restore_yarn_cache
      - run: yarn install
      - *save_yarn_cache
      - run: rm .npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
